{
'content_type': 'text',
'message_id': 95, 
'from_user': {'id': 326183269, 
			  'is_bot': False, 
			  'first_name': 'Mike', 
			  'username': None, 
			  'last_name': None, 
			  'language_code': 'en-us'
			  }, 
'date': 1535573515, 
'chat': {'type': 'private', 
		 'last_name': None, 
		 'first_name': 'Mike', 
		 'username': None, 
		 'id': 326183269, 
		 'title': None, 
		 'all_members_are_administrators': None, 
		 'photo': None, 
		 'description': None, 
		 'invite_link': None, 
		 'pinned_message': None, 
		 'sticker_set_name': None, 
		 'can_set_sticker_set': None
		}, 
'forward_from_chat': None, 
'forward_from': None, 
'forward_date': None, 
'reply_to_message': None, 
'edit_date': None, 
'media_group_id': None, 
'author_signature': None, 
'text': '/share_purchase', 
'entities': [<telebot.types.MessageEntity object at 0x7f351b399128>], 
'caption_entities': None, 
'audio': None, 
'document': None, 
'photo': None, 
'sticker': None, 
'video': None, 
'video_note': None, 
'voice': None, 
'caption': None, 
'contact': None, 
'location': None, 
'venue': None, 
'new_chat_member': None, 
'new_chat_members': None, 
'left_chat_member': None, 
'new_chat_title': None, 
'new_chat_photo': None, 
'delete_chat_photo': None, 
'group_chat_created': None, 
'supergroup_chat_created': None, 
'channel_chat_created': None, 
'migrate_to_chat_id': None, 
'migrate_from_chat_id': None, 
'pinned_message': None, 
'invoice': None, 
'successful_payment': None, 
'connected_website': None, 
'json': {'message_id': 95,
		 'from': {'id': 326183269, 
		 		  'is_bot': False, 
		 		  'first_name': 'Mike', 
		 		  'language_code': 'en-us'
		 		 }, 
'chat': {'id': 326183269,
		 'first_name': 'Mike',
		 'type': 'private'
		}, 
'date': 1535573515,
'text': '/share_purchase', 
'entities': [{'offset': 0, 
			  'length': 15, 
			  'type': 'bot_command'
			}]
		}}

{'content_type': 'location', 
'message_id': 559, 
'from_user': {'id': 326183269, 
			  'is_bot': False, 
			  'first_name': 'Mike', 
			  'username': None, 
			  'last_name': None, 
			  'language_code': 'en-us'
			},
'date': 1535632902,
'chat': {'type': 'private',
		 'last_name': None,
		 'first_name': 'Mike', 
		 'username': None, 
		 'id': 326183269, 
		 'title': None, 
		 'all_members_are_administrators': None, 
		 'photo': None, 'description': None, 'invite_link': None, 'pinned_message': None,
		  'sticker_set_name': None, 'can_set_sticker_set': None
		 }, 
'forward_from_chat': None, 
'forward_from': None, 
'forward_date': None, 
'reply_to_message': None, 
'edit_date': None, 
'media_group_id': None, 
'author_signature': None, 
'text': None, 
'entities': None, 
'caption_entities': None, 
'audio': None, 
'document': None, 'photo': None, 'sticker': None, 'video': None, 'video_note': None, 'voice': None, 'caption': None,
'contact': None, 
'location': {'longitude': 38.683617, 
			 'latitude': 8.989633
			}, 
'venue': None,
'new_chat_member': None, 
'new_chat_members': None, 
'left_chat_member': None,
'new_chat_title': None, 'new_chat_photo': None, 'delete_chat_photo': None, 'group_chat_created': None, 
'supergroup_chat_created': None, 'channel_chat_created': None, 'migrate_to_chat_id': None, 
'migrate_from_chat_id': None, 'pinned_message': None, 'invoice': None, 'successful_payment': None, 
'connected_website': None, 'json': {'message_id': 559, 'from': {'id': 326183269, 'is_bot': False, 'first_name': 'Mike', 'language_code': 'en-us'}, 'chat': {'id': 326183269, 'first_name': 'Mike', 'type': 'private'}, 'date': 1535632902, 'location': {'latitude': 8.989633, 'longitude': 38.683617}}}



CHAT

{'game_short_name': None, 
'chat_instance': '-1012078402783615373', 
'id': '1400946475728151716', 
'from_user': {'id': 326183269, 
			  'is_bot': False, 
			  'first_name': 'Mike', 
			  'username': None, 
			  'last_name': None, 
			  'language_code': 'en-us'
			}, 
'message': {'content_type': 'text', 
			'message_id': 1748, 
			'from_user': <telebot.types.User object at 0x7f9bf196fcf8>, 
			'date': 1535913275, 
			'chat': <telebot.types.Chat object at 0x7f9bf196fc50>, 
			'forward_from_chat': None, 
			'forward_from': None, 
			'forward_date': None, 
			'reply_to_message': <telebot.types.Message object at 0x7f9bf196fa20>, 
			'edit_date': None, 
			'media_group_id': None, 
			'author_signature': None, 
			'text': "Hello Mike.\nWhy don't you share your experience with your recent purchase?\n /share_purchase", 
			'entities': [<telebot.types.MessageEntity object at 0x7f9bf196f9e8>], 
			'caption_entities': None, 
			'audio': None, 
			'document': None, 
			'photo': None, 
			'sticker': None, 
			'video': None, 
			'video_note': None, 
			'voice': None, 
			'caption': None, 
			'contact': None, 
			'location': None, 
			'venue': None, 
			'new_chat_member': None, 
			'new_chat_members': None, 
			'left_chat_member': None, 
			'new_chat_title': None, 
			'new_chat_photo': None, 
			'delete_chat_photo': None, 
			'group_chat_created': None, 
			'supergroup_chat_created': None, 
			'channel_chat_created': None, 
			'migrate_to_chat_id': None, 
			'migrate_from_chat_id': None, 
			'pinned_message': None, 
			'invoice': None, 
			'successful_payment': None, 
			'connected_website': None, 
			'json': {'message_id': 1748, 
					 'from': {'id': 655462722, 
					 		  'is_bot': True, 
					 		  'first_name': 'Arada Buyer', 
					 		  'username': 'aradabuyerbot'
					 		 }, 
					 'chat': {'id': 326183269, 
					 		  'first_name': 'Mike', 
					 		  'type': 'private'
					 		 }, 
					 'date': 1535913275, 
					 'reply_to_message': {'message_id': 1747, 
					 					  'from': {'id': 326183269, 
					 					  		   'is_bot': False, 
					 					  		   'first_name': 'Mike', 
					 					  		   'language_code': 'en-us'
					 					  		   },
					 					   'chat': {'id': 326183269, 
					 					   			'first_name': 'Mike', 
					 					   			'type': 'private'
					 					   		    }, 
					 					   'date': 1535913273, 
					 					   'text': '/start', 
					 					   'entities': [{'offset': 0,
					 					   				 'length': 6, 
					 					   				 'type': 'bot_command'
					 					   				}]
					 					   				}, 
					 					   'text': "Hello Mike.\nWhy don't you share your experience with your recent purchase?\n /share_purchase", 
					 					   'entities': [{'offset': 76, 
					 					   				 'length': 15, 
					 					   				 'type': 'bot_command'
					 					   				}]
					 					   			}}, 
					 					   'data': 'store', 
					 					   'inline_message_id': None
					 					}